# Generated by Django 3.0.1 on 2020-03-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_result_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='prediction',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=70),
        ),
    ]
