# Generated by Django 3.0.1 on 2020-03-04 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0006_auto_20200304_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='filepath',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
